baseurl = "http://www.iasobiodelivery.com.br/"

title = "Iaso Biodelivery"
theme = "universal"
# themesDir = "../.."

isMultiLingual = true
# languageCode = "en-us"
languageCode = "pt-br"
# defaultContentLanguage = "en"
# defaultContentLanguage = "pt-br"
defaultContentLanguage = "pt"

# Enable comments by entering your Disqus shortname
# disqusShortname = "iasobiodelivery"
# Enable Google Analytics by entering your tracking code
googleAnalytics = "UA-127555031-1"

# Define the number of posts per page
paginate = 5

footnoteReturnLinkContents = "↑" # "↩"
summaryLength = 50  # 70


[blackfriday]
    fractions = false

# Portuguese ###############
[languages.pt]
    lang = "pt-br"
    languageCode = "pt-br"
    languagePrefix = "pt"
    contentDir = "content/pt"
    languageName = "Português"
    weight = 1
    # Navigation
    [languages.pt.menu]
        [[languages.pt.menu.main]]
            name = "Home"
            url  = "/"
            weight = 1
        # [[languages.pt.menu.main]]
        #     name = "Sobre"
        #     # identifier = "sobre"
        #     url  = "/sobre/"
        #     weight = 2
        [[languages.pt.menu.main]]
            name = "Novidades"
            # https://github.com/devcows/hugo-universal-theme/issues/46
            # https://github.com/devcows/hugo-universal-theme/issues/88
            # https://github.com/devcows/hugo-universal-theme/commit/12225a50bf043ff73639d932da2d7a525e53aced
            # url  = "/noticias/"
            url  = "/blog/"
            # identifier = "blog"
            weight = 2
        [[languages.pt.menu.main]]
            name = "Contato"
            url  = "/contato/"
            weight = 3
        # Top bar social links menu
        # FIXME Terá whatsapp?
        [[languages.pt.menu.topbar]]
            weight = 1
            name = "LinkedIn"
            url = "https://www.linkedin.com/company/iaso-biodelivery/"
            pre = "<i class='fa fa-2x fa-linkedin'></i>"
        [[languages.pt.menu.topbar]]
            weight = 2
            name = "Email"
            url = "mailto:contato@iasobiodelivery.com.br"
            pre = "<i class='fa fa-2x fa-envelope'></i>"

    # Params
    [languages.pt.params]
        defaultKeywords = ["iaso", "biodelivery", "implantes", "dispositivos médicos", "liberação de fármacos"]
        defaultDescription = "Empresa de desenvolvimento de dispositivos médicos com sistema de liberação de fármacos"
        # about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
        copyright = "&copy; 2019, Iaso Biodelivery; todos os direitos reservados."

        [languages.pt.params.contact]
            emailsSubjectPrefix = "[Iaso:Site]"
            thankyouPage = "obrigado"
            # FIXME Quer receber email em cópia?
            # emailCc = "izabellegindri@gmail.com"

        [languages.pt.params.testimonials]
            enable = true
            # All testimonials are defined in their own files at 'exampleSite/data/testimonials'.
            # TODO @Iza: Aqui o título vira "Produtos"?
            title = "Produtos em desenvolvimento"
            subtitle = "Implante subdérmico para o tratamento da Doença de Alzheimer."

        [languages.pt.params.see_more]
            enable = true
            icon = "fa fa-handshake-o"
            # icon = "fa fa-industry"
            # icon = "fa fa-microchip"
            title = "Investidores"
            subtitle = "Quer fazer parte da revolução em tratamentos de doenças crônicas?"
            link_url = "/contato"
            link_text = "Entre em contato"

        [languages.pt.params.clients]
            enable = true 
            # All clients are defined in their own files at 'exampleSite/data/clients'.
            title = "Sobre"
            subtitle = "Transformando soluções em saúde através da tecnologia de dispositivos médicos com sistemas de liberação de fármacos."
            description = "A Iaso **Biodelivery** atua ativamente no desenvolvimento de soluções em saúde através a utilização da tecnologia de dispositivos médicos com sistemas de liberação de fármacos. Está interessado? [Entre em contato.](/contato/)"
            link_url = "/sobre"

        [languages.pt.params.recent_posts]
            enable = true
            title = "Últimas novidades"
            # FIXME Mudar este texto
            # subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."

# English ###############
[languages.en]
    lang = "en"
    languageCode = "en-us"
    languagePrefix = "en"
    contentDir = "content/en"
    languageName = "English"
    weight = 2
    # Navigation
    [languages.en.menu]
        [[languages.en.menu.main]]
            name = "Home"
            url  = "/"
            weight = 1
        # [[languages.en.menu.main]]
        #     name = "news"
        #     url  = "/blog/"
        #     weight = 2
        [[languages.en.menu.main]]
            name = "Contact"
            url  = "/contact/"
            weight = 2
        # Top bar social links menu
        [[languages.en.menu.topbar]]
            weight = 1
            name = "LinkedIn"
            url = "https://www.linkedin.com/company/iaso-biodelivery/"
            pre = "<i class='fa fa-2x fa-linkedin'></i>"
        [[languages.en.menu.topbar]]
            weight = 2
            name = "Email"
            url = "mailto:contato@iasobiodelivery.com.br"
            pre = "<i class='fa fa-2x fa-envelope'></i>"

    # Params
    [languages.en.params]
        defaultKeywords = ["iaso", "biodelivery", "implantes", "medical devices", "controlled drugs doses release"]
        defaultDescription = "Implantable Drug-Delivery Platform"
        copyright = "&copy; 2019, Iaso Biodelivery; all rights reserved."

        [params.contact]
            emailsSubjectPrefix = "[Iaso:Site]"
            thankyouPage = "thankyou"
            # FIXME Quer receber email em cópia?
            # emailCc = "izabellegindri@gmail.com"

        [languages.en.params.testimonials]
            enable = true
            title = "Products"
            subtitle = "Subdermal Implant for Alzheimer's Disease treatment."

        [languages.en.params.see_more]
            enable = true
            icon = "fa fa-handshake-o"
            title = "Investors"
            subtitle = "Do you want to be part of the revolution in chronic disease treatments?"
            link_url = "/contact"
            link_text = "Get in touch"

        [languages.en.params.clients]
            enable = true
            title = "About"
            subtitle = "We have developed an Implantable Drug Delivery Platform (IDDD) for the treatment of Chronic Conditions."
            description = "<b>ADHESION</b><br>Improved Patient Compliance<br><br><b>LOCAL ACTION</b><br>Less-Side Effects due to Systemic Effects<br><br><b>LOWER DOSE</b><br>More efficacy and bioavailability."
            link_url = "/contact"

        [languages.en.params.recent_posts]
            enable = false
            title = "Latest news"


# Generic params (common for all languages)
[params]
    viewMorePostLink = "/blog/"
    # author = "Iaso Biodelivery"

    # Google Maps API key (if not set will default to not passing a key.)
    # googleMapsApiKey = "AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "red"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "contato@iasobiodelivery.com.br"

    show_social_links_on_footer = true

    # Format dates with Go's time formatting
    date_format = "2 January, 2006"

    # FIXME criar o favico
    # logo = "img/logo.svg"
    logo = "img/logo_text.svg"
    logo_small = "img/logo-small.svg"
    # SC-401, km 01, 600, Ed. CELTA - João Paulo, Florianópolis - SC, 88030-000, Brazil
    address = """<p><strong>Iaso Biodelivery</strong>
        <br>SC-401, km 01, 600
        <br>Ed. CELTA - João Paulo
        <br>88030-000
        <br>Florianópolis - SC - <strong>Brasil</strong>
      </p>
      """
    latitude = "-27.5711992"
    longitude = "-48.5090725"

[Permalinks]
    # blog = "/blog/:year/:month/:day/:filename/"
    blog = "/blog/:title/"


# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    # text = """<p class="hidden-sm hidden-xs">Nos contate por +420 777 555 333 or contato@iasobiodelivery.com.br.</p>
    #   <p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
    #   <a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
    #   </p>
    #   """

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false

[params.homepage]
    enable = true
    title = "Iaso Biodelivery"
    description = "<p>Implantable Drug-Delivery Platform</p>"

[params.carousel]
    enable = false
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = false
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.
